create table users (
	username		VARCHAR(50)		NOT NULL PRIMARY KEY,
	password		VARCHAR(500)	NOT NULL,
	role			CHAR(50)		DEFAULT 'ROLE_READONLY',
	register_at		DATETIME		DEFAULT CURRENT_TIMESTAMP,
	last_login_at	DATETIME 		DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	update_at		DATETIME		DEFAULT  CURRENT_TIMESTAMP
);